name: saude_mental
description: "Aplicativo de cadastro de clientes para saúde mental."

# A versão do aplicativo
version: 1.0.0+1

# Define o SDK do Dart necessário para este projeto
environment:
  sdk: ">=3.5.3 <4.0.0"

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  mysql1: ^0.19.1  # Biblioteca para conexão com o MySQL

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  # Seção de assets, descomente e adicione se houver imagens
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Seção de fontes personalizadas, descomente e configure se houver fontes personalizadas
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
